class PluginSettings(object):
    HUI_INGEST_FOLDER = 'histomicsui.ingest_folder'
    HUI_QUARANTINE_FOLDER = 'histomicsui.quarantine_folder'
    HUI_PROCESSED_FOLDER = 'histomicsui.processed_folder'
    HUI_REJECTED_FOLDER = 'histomicsui.rejected_folder'
    HUI_ORIGINAL_FOLDER = 'histomicsui.original_folder'
    HUI_FINISHED_FOLDER = 'histomicsui.finished_folder'
    HUI_REPORTS_FOLDER = 'histomicsui.reports_folder'
    WSI_DEID_IMPORT_PATH = 'wsi_deid.import_path'
    WSI_DEID_EXPORT_PATH = 'wsi_deid.export_path'
