---
services:
  girder:
    image: dsarchive/wsi_deid:v2.2.1
    # Set CURRENT_UID to your user id (e.g., `CURRENT_UID=$(id -u):$(id -g)`)
    # so that local file assetstores and logs are owned by yourself.
    # user: ${CURRENT_UID}
    restart: unless-stopped
    # Set DSA_PORT to expose the interface on another port (default 8080).
    ports:
      - "${DSA_PORT:-8080}:8080"
    environment:
      - GIRDER_CONFIG=/conf/girder.local.conf
    volumes:
      # Default assetstore
      - fsdata:/assetstore
      - logs:/logs
      # Change for local files:
      # - ./assetstore:/assetstore
      # - ./logs:/logs
      # Location of girder.local.conf and provision.py; add to use local
      # versions
      # - .:/conf
      # Add for import and export location.  This can also be done with a
      # docker-compose.local.yml file.  See the example.
      # - <some local path>:/import
      # - <some local path>:/export
      # Original pilot settings
      - ./girder.local.pilot.conf:/conf/girder.local.conf
      - ./importManifestSchema.pilot.json:/usr/local/lib/python3.9/dist-packages/wsi_deid/schema/importManifestSchema.json
    depends_on:
      - mongodb
      - memcached
  mongodb:
    image: "mongo:latest"
    # Set CURRENT_UID to your user id (e.g., `CURRENT_UID=$(id -u):$(id -g)`)
    # so that local file database and logs are owned by yourself.
    # user: ${CURRENT_UID}
    restart: unless-stopped
    volumes:
      # Location to store database files
      # Change for local files:
      # - ./db:/data/db
      # - ./logs:/var/log/mongodb
      - dbdata:/data/db
  memcached:
    image: memcached
    command: -m 4096
    restart: unless-stopped

volumes:
  dbdata:
  fsdata:
  logs:
